name: C/C++ CI

on:
  push:
    branches: [ stable, CI-work ]
  pull_request:
    branches: [ stable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: sudo apt install parted mtools
    - name: build
      run: sudo sh ./scripts/ci.sh
    - name: gen-x86_32-image
      run: |
        mkdir -p iso32/boot/grub
        cp build32/krnl iso32/boot/krnl
        cp extra/grub.cfg iso32/boot/grub/grub.cfg
        grub-mkrescue -o Night-x86_32-CI.iso
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: Night-x86_32-CI.iso
        # A file, directory or wildcard pattern that describes what to upload
        path: ./Night-x86_32-CI.iso

