name: C/C++ CI

on:
  push:
    branches: [ stable, CI-work ]
  pull_request:
    branches: [ stable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: sudo apt install parted
    - name: build
      run: sudo sh ./scripts/ci.sh
    - name: gen-x86_32-image
      run: |
        mkdir -p iso32/boot/grub
        cp build32/krnl iso32/boot/krnl
        cp extra/grub.cfg iso32/boot/grub/grub.cfg
        grub-mkrescue -o Night-x86_32-CI.iso
